# https://esphome.io/components/sensor/ld2410.html

uart:
  tx_pin: "${uart_tx_pin}"
  rx_pin: "${uart_rx_pin}"
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:

number:
  - platform: ld2410
    timeout:
      name: "mmWave Timeout"
    light_threshold:
      name: "mmWave Light Threshold"
    max_move_distance_gate:
      name: "mmWave Max Move Distance Gate"
    max_still_distance_gate:
      name: "mmWave Max Still Distance Gate"
    g0:
      move_threshold:
        name: "mmWave g0 move threshold"
      still_threshold:
        name: "mmWave g0 still threshold"
    g1:
      move_threshold:
        name: "mmWave g1 move threshold"
      still_threshold:
        name: "mmWave g1 still threshold"
    g2:
      move_threshold:
        name: "mmWave g2 move threshold"
      still_threshold:
        name: "mmWave g2 still threshold"
    g3:
      move_threshold:
        name: "mmWave g3 move threshold"
      still_threshold:
        name: "mmWave g3 still threshold"
    g4:
      move_threshold:
        name: "mmWave g4 move threshold"
      still_threshold:
        name: "mmWave g4 still threshold"
    g5:
      move_threshold:
        name: "mmWave g5 move threshold"
      still_threshold:
        name: "mmWave g5 still threshold"
    g6:
      move_threshold:
        name: "mmWave g6 move threshold"
      still_threshold:
        name: "mmWave g6 still threshold"
    g7:
      move_threshold:
        name: "mmWave g7 move threshold"
      still_threshold:
        name: "mmWave g7 still threshold"
    g8:
      move_threshold:
        name: "mmWave g8 move threshold"
      still_threshold:
        name: "mmWave g8 still threshold"

binary_sensor:
  - platform: ld2410
    has_target:
      name: "mmWave"
      id: motion_mmwave
    has_moving_target:
      name: "mmWave Moving Target"
    has_still_target:
      name: "mmWave Still Target"
    out_pin_presence_status:
      name: "mmWave out pin presence status"

sensor:
  - platform: ld2410
    light:
      name: light
    moving_distance:
      name: "mmWave Moving Distance"
    still_distance:
      name: "mmWave Still Distance"
    moving_energy:
      name: "mmWave Move Energy"
    still_energy:
      name: "mmWave Still Energy"
    detection_distance:
      name: "mmWave Detection Distance"
    g0:
      move_energy:
        name: "mmWave g0 move energy"
      still_energy:
        name: "mmWave g0 still energy"
    g1:
      move_energy:
        name: "mmWave g1 move energy"
      still_energy:
        name: "mmWave g1 still energy"
    g2:
      move_energy:
        name: "mmWave g2 move energy"
      still_energy:
        name: "mmWave g2 still energy"
    g3:
      move_energy:
        name: "mmWave g3 move energy"
      still_energy:
        name: "mmWave g3 still energy"
    g4:
      move_energy:
        name: "mmWave g4 move energy"
      still_energy:
        name: "mmWave g4 still energy"
    g5:
      move_energy:
        name: "mmWave g5 move energy"
      still_energy:
        name: "mmWave g5 still energy"
    g6:
      move_energy:
        name: "mmWave g6 move energy"
      still_energy:
        name: "mmWave g6 still energy"
    g7:
      move_energy:
        name: "mmWave g7 move energy"
      still_energy:
        name: "mmWave g7 still energy"
    g8:
      move_energy:
        name: "mmWave g8 move energy"
      still_energy:
        name: "mmWave g8 still energy"

switch:
  - platform: ld2410
    engineering_mode:
      name: "mmWave Engineering Mode"
    bluetooth:
      name: "mmWave Bluetooth"

button:
  - platform: ld2410
    factory_reset:
      name: "mmWave Factory Reset"
    restart:
      name: "mmWave Restart"
    query_params:
      name: "mmWave Force Refresh"

text_sensor:
  - platform: ld2410
    version:
      name: "mmWave Firmware Version"
    mac_address:
      name: "mmWave Mac Address"

select:
  - platform: ld2410
    distance_resolution:
      name: "mmWave Distance Resolution"
    baud_rate:
      name: "mmWave Baud Tate"
    light_function:
      name: "mmWave Light Function"
    out_pin_level:
      name: "mmWave Out Pin Level"
