uart:
  id: uart_bus
  tx_pin: "${uart_tx_pin}"
  rx_pin: "${uart_rx_pin}"
  baud_rate: 115200

dfrobot_sen0395:
  uart_id: uart_bus

binary_sensor:
  - platform: gpio
    name: "mmWave"
    id: motion_mmwave
    device_class: occupancy
    pin:
      number: "${sen0395_io_pin}"
      mode: INPUT_PULLDOWN

switch:
  - platform: dfrobot_sen0395
    name: "mmWave Sensor"
    type: sensor_active

  - platform: dfrobot_sen0395
    name: "mmWave Presence Via Uart"
    type: presence_via_uart
    disabled_by_default: true

  - platform: dfrobot_sen0395
    name: "mmWave Autostart"
    type: start_after_boot
    disabled_by_default: true

  - platform: dfrobot_sen0395
    name: "mmWave LED"
    type: turn_on_led

number:
  - platform: template
    name: "mmWave Sensitivity"
    id: mmwave_sensitivity
    entity_category: config
    min_value: 0
    max_value: 9
    initial_value: 7
    optimistic: true
    step: 1
    restore_value: true

  - platform: template
    name: "mmWave Off Latency"
    id: mmwave_off_latency
    entity_category: config
    min_value: 0
    max_value: 60
    initial_value: 10
    optimistic: true
    step: 0.025
    restore_value: true
    unit_of_measurement: s
    mode: box

  - platform: template
    name: "mmWave On Latency"
    id: mmwave_on_latency
    entity_category: config
    min_value: 0
    max_value: 60
    initial_value: 2.5
    optimistic: true
    step: 0.025
    restore_value: true
    unit_of_measurement: s
    mode: box

  - platform: template
    name: "mmWave Segment 1 Begin"
    id: mmwave_segment_1_begin
    entity_category: config
    min_value: 0
    max_value: 9
    initial_value: 0
    optimistic: true
    step: 0.15
    restore_value: true
    unit_of_measurement: m
    mode: BOX

  - platform: template
    name: "mmWave Segment 1 End"
    id: mmwave_segment_1_end
    entity_category: config
    min_value: 0
    max_value: 9
    initial_value: 3
    optimistic: true
    step: 0.15
    restore_value: true
    unit_of_measurement: m
    mode: BOX

  - platform: template
    name: "mmWave Segment 2 Begin"
    id: mmwave_segment_2_begin
    entity_category: config
    min_value: 0
    max_value: 9
    initial_value: 0
    optimistic: true
    step: 0.15
    restore_value: true
    unit_of_measurement: m
    mode: BOX

  - platform: template
    name: "mmWave Segment 2 End"
    id: mmwave_segment_2_end
    entity_category: config
    min_value: 0
    max_value: 9
    initial_value: 0
    optimistic: true
    step: 0.15
    restore_value: true
    unit_of_measurement: m
    mode: BOX

  - platform: template
    name: "mmWave Segment 3 Begin"
    id: mmwave_segment_3_begin
    entity_category: config
    min_value: 0
    max_value: 9
    initial_value: 0
    optimistic: true
    step: 0.15
    restore_value: true
    unit_of_measurement: m
    mode: BOX

  - platform: template
    name: "mmWave Segment 3 End"
    id: mmwave_segment_3_end
    entity_category: config
    min_value: 0
    max_value: 9
    initial_value: 0
    optimistic: true
    step: 0.15
    restore_value: true
    unit_of_measurement: m
    mode: BOX

  - platform: template
    name: "mmWave Segment 4 Begin"
    id: mmwave_segment_4_begin
    entity_category: config
    min_value: 0
    max_value: 9
    initial_value: 0
    optimistic: true
    step: 0.15
    restore_value: true
    unit_of_measurement: m
    mode: BOX

  - platform: template
    name: "mmWave Segment 4 End"
    id: mmwave_segment_4_end
    entity_category: config
    min_value: 0
    max_value: 9
    initial_value: 0
    optimistic: true
    step: 0.15
    restore_value: true
    unit_of_measurement: m
    mode: BOX

  - platform: template
    name: "mmWave Segments"
    id: mmwave_segments
    entity_category: config
    min_value: 1
    max_value: 4
    initial_value: 1
    optimistic: true
    step: 1
    restore_value: true
    mode: SLIDER

button:
  - platform: template
    name: "mmWave Factory Reset"
    entity_category: diagnostic
    on_press:
      - dfrobot_sen0395.settings:
          factory_reset: true

  - platform: template
    name: "mmWave Restart"
    entity_category: diagnostic
    on_press:
      - dfrobot_sen0395.reset

  - platform: template
    name: "mmWave Apply Settings"
    entity_category: config
    on_press:
      - dfrobot_sen0395.settings:
          sensitivity: !lambda return id(mmwave_sensitivity).state;
          detection_segments:
            - !lambda return id(mmwave_segment_1_begin).state;
            - !lambda return id(mmwave_segment_1_end).state;

            - !lambda if(id(mmwave_segments).state >= 2){ return id(mmwave_segment_2_begin).state; } else { return -1; };
            - !lambda if(id(mmwave_segments).state >= 2){ return id(mmwave_segment_2_end).state; } else { return -1; };

            - !lambda if(id(mmwave_segments).state >= 3){ return id(mmwave_segment_3_begin).state; } else { return -1; };
            - !lambda if(id(mmwave_segments).state >= 3){ return id(mmwave_segment_3_end).state; } else { return -1; };

            - !lambda if(id(mmwave_segments).state == 4){ return id(mmwave_segment_4_begin).state; } else { return -1; };
            - !lambda if(id(mmwave_segments).state == 4){ return id(mmwave_segment_4_end).state; } else { return -1; };
          output_latency:
            delay_after_detect: !lambda return id(mmwave_on_latency).state;
            delay_after_disappear: !lambda return id(mmwave_off_latency).state;
