---
# Wi-Fi component package
# https://esphome.io/components/wifi.html
#

substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_pwd
  wifi_ap_password: !secret wifi_fallback_ssid_password
  host_name: "${host_name}"

wifi:
  id: component_wifi
  ssid: "${wifi_ssid}"
  use_address: "${host_name}"
  password: "${wifi_password}"
  reboot_timeout: 10min
  ap:
    ssid: "${friendly_name} AP"
    password: "${wifi_ap_password}"

sensor:
  - <<: !include ../sensors/wifi_signal_percentage.yaml
  - <<: !include ../sensors/wifi_signal.yaml
    on_value:
      - component.update: sensor_wifi_signal_percentage

text_sensor:
  - <<: !include ../text_sensors/wifi_info.yaml