---
# Device: C3 Mini board
#

substitutions:
  buzzer_pin: A0
  i2s_bclk_pin: A1
  i2s_din_pin: "${buzzer_pin}"
  i2s_lrclk_pin: A5
  pir_pin: A4
  rgb_led_pin: GPIO7
  rgb_led_type: GRB
  sen0395_io_pin: A2
  uart_rx_pin: GPIO20
  uart_tx_pin: GPIO21

packages:
  <<: !include_dir_named ../components/common
  wifi: !include ../components/hardware/wifi.yaml
  board: !include ../boards/c3_mini.yaml
  mosquitto: !include ../components/integrations/mqtt.yaml

  ## Sensors
  bh1750: !include ../components/sensors/bh1750.yaml
  bme680: !include ../components/sensors/bme68x_bsec.yaml
  buzzer: !include ../components/sensors/buzzer.yaml
  occupancy: !include ../components/sensors/occupancy.yaml
  pir: !include ../components/sensors/pir.yaml
  rgb_led: !include ../components/sensors/rgb_led.yaml
  sen0395: !include ../components/sensors/sen0395.yaml
