substitutions:
  buzzer_pin: A0
  i2s_bclk_pin: A1
  i2s_din_pin: "${buzzer_pin}"
  i2s_lrclk_pin: A5
  pir_pin: A4
  rgb_led_pin: GPIO7
  rgb_led_type: GRB
  sen0395_io_pin: A2
  uart_rx_pin: GPIO20
  uart_tx_pin: GPIO21

esphome:
  platformio_options:
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"
    board_build.flash_mode: dio

esp32:
  board: lolin_c3_mini
  variant: ESP32C3

wifi:
  output_power: 8.5dBm

i2c:
  sda: GPIO8
  scl: GPIO10

sensor:
  - platform: internal_temperature
    name: "CPU Temperature"
